spring.application.name=DBTest

# H2 Database 설정 (인메모리 DB)
# spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# Update 쿼리에 WHERE 가 없다면? - 에러 확인을 위해 락 대기 시간을 짧게 설정
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=2000
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# JPA / Hibernate 설정
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.data.redis.host=localhost
spring.data.redis.port=6379

